export const SLIDES = [
  '/slides/1.png',
  {
    src: '/slides/2.png',
    link: 'https://www.youtube.com/watch?v=zH6cG-DptYM',
    linkText: 'Algunas historias no se cuentan para explicar la vida. Se cuenta para intentar entenderla.',
    linkClassName: 'slide-viewer-link-2',
    showClickIcon: true,
  },
  '/slides/3.png',
  '/slides/4.png',
  {
    src: '/slides/5.png',
    link: 'https://www.youtube.com/watch?v=kQvBakkddBk',
    linkText: 'No todas las personas pueden acceder a este "mapa emocional" con la misma claridad.',
    linkClassName: 'slide-viewer-link-5',    

    extraLink: 'https://www.psicologosmadrid-ipsia.com/la-rueda-de-las-emociones/',
    extraText: 'Click para visitar la rueda de emociones',
    extraClassName: 'slide-viewer-extra-5',
    showClickIcon: true,
  },
  {
    src: '/slides/6.png',
    audioSrc: '/Audio-psicologa.mp4',
    linkText: 'Audio Sara María Osorio',
    linkClassName: 'slide-viewer-link-6',
    showClickIcon: true,
  },
  '/slides/7.png',
  '/slides/8.png',
  '/slides/9.mp4',
  '/slides/10.png',
  '/slides/11.png',
  '/slides/12.png',
];
